name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: 'none'
version: 2.0.7+4

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  # for local file test
  dio: ^4.0.0
  path_provider: ^2.0.2 # removed this because it cancel flutter/android/ios on pub.dev path_provider: ^1.6.10

  http: ^0.13.3 #to download / cache network files
  provider: ^5.0.0

  file: ^6.1.2

  flutter_audio_query: ^0.3.4+1
  assets_audio_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: 3.0.0

  # uncomment to use remote repos
  #assets_audio_player: ^2.0.1
  # assets_audio_player_web: 1.3.5+3

  # uncomment to match local repos
  #assets_audio_player_web:
  #  path: ../assets_audio_player_web

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family:  AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
